INSERT INTO course_lessons (id, module_id, course_id, title, order_index, type, content_type, is_preview, is_free_preview) VALUES
('les-t1-1.1', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.1: Chào Mừng Đến GEM Trading Academy', 0, 'article', 'html', false, false),
('les-t1-1.2', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.2: Nguyên Lý Cốt Lõi - Mất Cân Bằng Cung Cầu', 1, 'article', 'html', false, false),
('les-t1-1.3', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.3: Smart Money và Retail Traders', 2, 'article', 'html', false, false),
('les-t1-1.4', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.4: Zone và Support/Resistance Truyền Thống', 3, 'article', 'html', false, false),
('les-t1-1.5', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.5: Tổng Quan 6 Công Thức Frequency Độc Quyền', 4, 'article', 'html', false, false),
('les-t1-1.6', 'mod-t1-ch1', 'course-tier1-trading-foundation', 'Bài 1.6: Nguyên Tắc Vàng - Đợi Retest', 5, 'article', 'html', false, false),
('les-t1-2.1', 'mod-t1-ch2', 'course-tier1-trading-foundation', 'Bài 2.1: HFZ (High Frequency Zone) Là Gì?', 0, 'article', 'html', false, false),
('les-t1-2.2', 'mod-t1-ch2', 'course-tier1-trading-foundation', 'Bài 2.2: LFZ (Low Frequency Zone) Là Gì?', 1, 'article', 'html', false, false),
('les-t1-2.3', 'mod-t1-ch2', 'course-tier1-trading-foundation', 'Bài 2.3: Cách Nhận Diện Zone Trên Biểu Đồ', 2, 'article', 'html', false, false),
('les-t1-2.4', 'mod-t1-ch2', 'course-tier1-trading-foundation', 'Bài 2.4: Nguyên Tắc Giao Dịch Với Zone', 3, 'article', 'html', false, false),
('les-t1-2.5', 'mod-t1-ch2', 'course-tier1-trading-foundation', 'Bài 2.5: Giới Hạn TIER 1 và Preview TIER 2', 4, 'article', 'html', false, false),
('les-t1-3.1', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.1: Tổng Quan Classic Patterns', 0, 'article', 'html', false, false),
('les-t1-3.2', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.2: Flag & Pennant Patterns', 1, 'article', 'html', false, false),
('les-t1-3.3', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.3: Triangle Patterns', 2, 'article', 'html', false, false),
('les-t1-3.4', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.4: Head & Shoulders Pattern', 3, 'article', 'html', false, false),
('les-t1-3.5', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.5: Double Top & Double Bottom', 4, 'article', 'html', false, false),
('les-t1-3.6', 'mod-t1-ch3', 'course-tier1-trading-foundation', 'Bài 3.6: Classic Patterns Tổng Kết', 5, 'article', 'html', false, false),
('les-t1-4.1', 'mod-t1-ch4', 'course-tier1-trading-foundation', 'Bài 4.1: Shooting Star (Sao Băng)', 0, 'article', 'html', false, false),
('les-t1-4.2', 'mod-t1-ch4', 'course-tier1-trading-foundation', 'Bài 4.2: Hanging Man (Người Treo Cổ)', 1, 'article', 'html', false, false),
('les-t1-4.3', 'mod-t1-ch4', 'course-tier1-trading-foundation', 'Bài 4.3: Hammer & Inverted Hammer', 2, 'article', 'html', false, false),
('les-t1-4.4', 'mod-t1-ch4', 'course-tier1-trading-foundation', 'Bài 4.4: Kết Hợp Patterns Với HFZ/LFZ', 3, 'article', 'html', false, false),
('les-t1-4.5', 'mod-t1-ch4', 'course-tier1-trading-foundation', 'Bài 4.5: Ôn Tập Tổng Hợp 5 Classic Patterns', 4, 'article', 'html', false, false),
('les-t1-5.1', 'mod-t1-ch5', 'course-tier1-trading-foundation', 'Bài 5.1: Paper Trading Là Gì?', 0, 'article', 'html', false, false),
('les-t1-5.2', 'mod-t1-ch5', 'course-tier1-trading-foundation', 'Bài 5.2: Hướng Dẫn Paper Trade Trong GEM App', 1, 'article', 'html', false, false),
('les-t1-5.3', 'mod-t1-ch5', 'course-tier1-trading-foundation', 'Bài 5.3: Trading Journal & Ghi Chép Giao Dịch', 2, 'article', 'html', false, false),
('les-t1-5.4', 'mod-t1-ch5', 'course-tier1-trading-foundation', 'Bài 5.4: Backtesting Cơ Bản', 3, 'article', 'html', false, false),
('les-t1-5.5', 'mod-t1-ch5', 'course-tier1-trading-foundation', 'Bài 5.5: Từ Paper Trading Đến Giao Dịch Thật', 4, 'article', 'html', false, false),
('les-t1-6.1', 'mod-t1-ch6', 'course-tier1-trading-foundation', 'Bài 6.1: Giới Thiệu GEM Master AI', 0, 'article', 'html', false, false),
('les-t1-6.2', 'mod-t1-ch6', 'course-tier1-trading-foundation', 'Bài 6.2: Sử Dụng Chatbot Hỏi Đáp', 1, 'article', 'html', false, false),
('les-t1-6.3', 'mod-t1-ch6', 'course-tier1-trading-foundation', 'Bài 6.3: Scanner Cơ Bản - Tìm Patterns Tự Động', 2, 'article', 'html', false, false),
('les-t1-6.4', 'mod-t1-ch6', 'course-tier1-trading-foundation', 'Bài 6.4: Thiết Lập Cảnh Báo', 3, 'article', 'html', false, false),
('les-t1-6.5', 'mod-t1-ch6', 'course-tier1-trading-foundation', 'Bài 6.5: Tổng Kết TIER 1 & Xem Trước TIER 2', 4, 'article', 'html', false, false),
('les-t1-7.1', 'mod-t1-ch7', 'course-tier1-trading-foundation', 'Bài 7.1: Con Người Cũ và Con Người Mới', 0, 'article', 'html', false, false),
('les-t1-7.2', 'mod-t1-ch7', 'course-tier1-trading-foundation', 'Bài 7.2: Bản Đồ Hành Trình Của Bạn', 1, 'article', 'html', false, false),
('les-t1-7.3', 'mod-t1-ch7', 'course-tier1-trading-foundation', 'Bài 7.3: Sự Thay Đổi Thực Sự', 2, 'article', 'html', false, false),
('les-t1-7.4', 'mod-t1-ch7', 'course-tier1-trading-foundation', 'Bài 7.4: Điều Khiến Bạn Khác Biệt', 3, 'article', 'html', false, false),
('les-t1-8.1', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.1: Ngã Ba Đường - Bạn Đang Đứng Ở Đâu?', 0, 'article', 'html', false, false),
('les-t1-8.2', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.2: Công Cụ Tăng Tốc - TIER 2 & TIER 3', 1, 'article', 'html', false, false),
('les-t1-8.3', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.3: Cơ Hội Đối Tác (CTV, KOL, Instructor)', 2, 'article', 'html', false, false),
('les-t1-8.4', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.4: Câu Chuyện Thành Công', 3, 'article', 'html', false, false),
('les-t1-8.5', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.5: Lợi Thế Đi Sớm', 4, 'article', 'html', false, false),
('les-t1-8.6', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.6: Khung Quyết Định', 5, 'article', 'html', false, false),
('les-t1-8.7', 'mod-t1-ch8', 'course-tier1-trading-foundation', 'Bài 8.7: Các Bước Tiếp Theo', 6, 'article', 'html', false, false),
('les-t2-1.1', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.1: DPD Là Gì?', 0, 'article', 'html', false, false),
('les-t2-1.2', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.2: Cấu Trúc 3 Phases Của DPD', 1, 'article', 'html', false, false),
('les-t2-1.3', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.3: Cách Vẽ HFZ Từ DPD', 2, 'article', 'html', false, false),
('les-t2-1.4', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.4: Chiến Lược Entry Cho DPD', 3, 'article', 'html', false, false),
('les-t2-1.5', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.5: Checklist Xác Nhận DPD', 4, 'article', 'html', false, false),
('les-t2-1.6', 'mod-t2-ch1', 'course-tier2-trading-advanced', 'Bài 1.6: Ví Dụ Thực Tế DPD', 5, 'article', 'html', false, false),
('les-t2-2.1', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.1: UPU Là Gì?', 0, 'article', 'html', false, false),
('les-t2-2.2', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.2: Cấu Trúc 3 Phases Của UPU', 1, 'article', 'html', false, false),
('les-t2-2.3', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.3: Cách Vẽ LFZ Từ UPU', 2, 'article', 'html', false, false),
('les-t2-2.4', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.4: Chiến Lược Entry Cho UPU', 3, 'article', 'html', false, false),
('les-t2-2.5', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.5: Checklist Xác Nhận UPU', 4, 'article', 'html', false, false),
('les-t2-2.6', 'mod-t2-ch2', 'course-tier2-trading-advanced', 'Bài 2.6: Ví Dụ Thực Tế UPU', 5, 'article', 'html', false, false),
('les-t2-3.1', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.1: UPD Là Gì?', 0, 'article', 'html', false, false),
('les-t2-3.2', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.2: Cấu Trúc 3 Phases Của UPD', 1, 'article', 'html', false, false),
('les-t2-3.3', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.3: Tại Sao UPD Là Pattern Mạnh?', 2, 'article', 'html', false, false),
('les-t2-3.4', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.4: Chiến Lược Entry Cho UPD', 3, 'article', 'html', false, false),
('les-t2-3.5', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.5: Phân Biệt UPD và DPD', 4, 'article', 'html', false, false),
('les-t2-3.6', 'mod-t2-ch3', 'course-tier2-trading-advanced', 'Bài 3.6: Ví Dụ Thực Tế UPD', 5, 'article', 'html', false, false),
('les-t2-4.1', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.1: DPU Pattern Là Gì?', 0, 'article', 'html', false, false),
('les-t2-4.2', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.2: Cấu Trúc 3 Phases Của DPU', 1, 'article', 'html', false, false),
('les-t2-4.3', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.3: Cách Vẽ LFZ Chính Xác', 2, 'article', 'html', false, false),
('les-t2-4.4', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.4: Chiến Lược Entry DPU', 3, 'article', 'html', false, false),
('les-t2-4.5', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.5: DPU Checklist 8 Điểm', 4, 'article', 'html', false, false),
('les-t2-4.6', 'mod-t2-ch4', 'course-tier2-trading-advanced', 'Bài 4.6: Ví Dụ Thực Tế DPU', 5, 'article', 'html', false, false),
('les-t2-5.1', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.1: HFZ Là Gì?', 0, 'article', 'html', false, false),
('les-t2-5.2', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.2: Cách Vẽ HFZ Chính Xác', 1, 'article', 'html', false, false),
('les-t2-5.3', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.3: Vòng Đời Zone (Zone Lifecycle)', 2, 'article', 'html', false, false),
('les-t2-5.4', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.4: Chiến Lược Entry Tại HFZ', 3, 'article', 'html', false, false),
('les-t2-5.5', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.5: Kết Hợp HFZ Với Đa Khung Thời Gian', 4, 'article', 'html', false, false),
('les-t2-5.6', 'mod-t2-ch5', 'course-tier2-trading-advanced', 'Bài 5.6: Ví Dụ Thực Tế HFZ', 5, 'article', 'html', false, false),
('les-t2-6.1', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.1: LFZ Là Gì?', 0, 'article', 'html', false, false),
('les-t2-6.2', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.2: Cách Vẽ LFZ Chính Xác', 1, 'article', 'html', false, false),
('les-t2-6.3', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.3: Xác Nhận Entry Tại LFZ', 2, 'article', 'html', false, false),
('les-t2-6.4', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.4: So Sánh HFZ và LFZ', 3, 'article', 'html', false, false),
('les-t2-6.5', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.5: Kết Hợp LFZ Với Classic Patterns', 4, 'article', 'html', false, false),
('les-t2-6.6', 'mod-t2-ch6', 'course-tier2-trading-advanced', 'Bài 6.6: Ví Dụ Thực Tế LFZ', 5, 'article', 'html', false, false),
('les-t2-7.1', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.1: Doji Patterns - Dragonfly & Gravestone', 0, 'article', 'html', false, false),
('les-t2-7.2', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.2: Rounding Bottom - Cup-shaped Bullish Reversal', 1, 'article', 'html', false, false),
('les-t2-7.3', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.3: Rounding Top - Cup-shaped Bearish Reversal', 2, 'article', 'html', false, false),
('les-t2-7.4', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.4: Ascending Triangle - Tam Giác Tăng', 3, 'article', 'html', false, false),
('les-t2-7.5', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.5: Descending Triangle - Tam Giác Giảm', 4, 'article', 'html', false, false),
('les-t2-7.6', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.6: Symmetrical Triangle - Tam Giác Cân', 5, 'article', 'html', false, false),
('les-t2-7.7', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.7: Kết Hợp Triangles Với GEM Zones', 6, 'article', 'html', false, false),
('les-t2-7.8', 'mod-t2-ch7', 'course-tier2-trading-advanced', 'Bài 7.8: Ví Dụ Thực Tế Triangle Patterns', 7, 'article', 'html', false, false),
('les-t2-8.1', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.1: Nguyên Tắc Đa Khung Thời Gian - Tier 2', 0, 'article', 'html', false, false),
('les-t2-8.2', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.2: Hệ Thống 3 Khung Thời Gian - Tier 2', 1, 'article', 'html', false, false),
('les-t2-8.3', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.3: Zone Hierarchy - Tier 2', 2, 'article', 'html', false, false),
('les-t2-8.4', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.4: Entry Chính Xác Trên LTF - Tier 2', 3, 'article', 'html', false, false),
('les-t2-8.5', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.5: Ví Dụ Thực Tế Multi-TF - Tier 2', 4, 'article', 'html', false, false),
('les-t2-8.6', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.6: Công Thức Tính Khối Lượng Lệnh - Tier 2', 5, 'article', 'html', false, false),
('les-t2-8.7', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.7: Đặt Stop Loss Đúng Cách - Tier 2', 6, 'article', 'html', false, false),
('les-t2-8.8', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.8: Chiến Lược Take Profit', 7, 'article', 'html', false, false),
('les-t2-8.9', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.9: Quy Tắc "Nhìn Sang Phải"', 8, 'article', 'html', false, false),
('les-t2-8.10', 'mod-t2-ch8', 'course-tier2-trading-advanced', 'Bài 8.10: Tổng Kết & Xem Trước TIER 3', 9, 'article', 'html', false, false),
('les-t2-9.1', 'mod-t2-ch9', 'course-tier2-trading-advanced', 'Bài 9.1: Hệ Thống Chấm Điểm Zone - Tier 2', 0, 'article', 'html', false, false),
('les-t2-9.2', 'mod-t2-ch9', 'course-tier2-trading-advanced', 'Bài 9.2: Odds Enhancers - Tier 2', 1, 'article', 'html', false, false),
('les-t2-9.3', 'mod-t2-ch9', 'course-tier2-trading-advanced', 'Bài 9.3: Zone Scoring Worksheet - Tier 2', 2, 'article', 'html', false, false),
('les-t2-9.4', 'mod-t2-ch9', 'course-tier2-trading-advanced', 'Bài 9.4: Filter Zones Trên Scanner - Tier 2', 3, 'article', 'html', false, false),
('les-t2-9.5', 'mod-t2-ch9', 'course-tier2-trading-advanced', 'Bài 9.5: Ví Dụ Thực Tế Zone Grading - Tier 2', 4, 'article', 'html', false, false),
('les-t2-10.1', 'mod-t2-ch10', 'course-tier2-trading-advanced', 'Bài 10.1: Con Người Cũ và Con Người Mới', 0, 'article', 'html', false, false),
('les-t2-10.2', 'mod-t2-ch10', 'course-tier2-trading-advanced', 'Bài 10.2: Bản Đồ Hành Trình', 1, 'article', 'html', false, false),
('les-t2-10.3', 'mod-t2-ch10', 'course-tier2-trading-advanced', 'Bài 10.3: Sự Thay Đổi Thực Sự', 2, 'article', 'html', false, false),
('les-t2-10.4', 'mod-t2-ch10', 'course-tier2-trading-advanced', 'Bài 10.4: Điều Khiến Bạn Khác Biệt', 3, 'article', 'html', false, false),
('les-t2-11.1', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.1: Ngã Ba Đường', 0, 'article', 'html', false, false),
('les-t2-11.2', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.2: Công Cụ Tăng Tốc', 1, 'article', 'html', false, false),
('les-t2-11.3', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.3: Cơ Hội Đối Tác', 2, 'article', 'html', false, false),
('les-t2-11.4', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.4: Câu Chuyện Thành Công', 3, 'article', 'html', false, false),
('les-t2-11.5', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.5: Lợi Thế Đi Sớm', 4, 'article', 'html', false, false),
('les-t2-11.6', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.6: Khung Quyết Định - Module B', 5, 'article', 'html', false, false),
('les-t2-11.7', 'mod-t2-ch11', 'course-tier2-trading-advanced', 'Bài 11.7: Các Bước Tiếp Theo - Module B', 6, 'article', 'html', false, false),
('les-t3-1.1', 'mod-t3-ch1', 'course-tier3-trading-mastery', 'Bài 1.1: Flag Pattern Là Gì?', 0, 'article', 'html', false, false),
('les-t3-1.2', 'mod-t3-ch1', 'course-tier3-trading-mastery', 'Bài 1.2: Bullish vs Bearish Flag', 1, 'article', 'html', false, false),
('les-t3-1.3', 'mod-t3-ch1', 'course-tier3-trading-mastery', 'Bài 1.3: Pennant Pattern', 2, 'article', 'html', false, false),
('les-t3-1.4', 'mod-t3-ch1', 'course-tier3-trading-mastery', 'Bài 1.4: Trading Flag & Pennant', 3, 'article', 'html', false, false),
('les-t3-1.5', 'mod-t3-ch1', 'course-tier3-trading-mastery', 'Bài 1.5: Ví Dụ Thực Tế Flag & Pennant', 4, 'article', 'html', false, false),
('les-t3-2.1', 'mod-t3-ch2', 'course-tier3-trading-mastery', 'Bài 2.1: Rising Wedge - Cái Nêm Tăng', 0, 'article', 'html', false, false),
('les-t3-2.2', 'mod-t3-ch2', 'course-tier3-trading-mastery', 'Bài 2.2: Falling Wedge - Cái Nêm Giảm', 1, 'article', 'html', false, false),
('les-t3-2.3', 'mod-t3-ch2', 'course-tier3-trading-mastery', 'Bài 2.3: Wedge vs Triangle - Phân Biệt', 2, 'article', 'html', false, false),
('les-t3-2.4', 'mod-t3-ch2', 'course-tier3-trading-mastery', 'Bài 2.4: Ví Dụ Thực Tế Wedge Patterns', 3, 'article', 'html', false, false),
('les-t3-3.1', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.1: Doji và Spinning Top', 0, 'article', 'html', false, false),
('les-t3-3.2', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.2: Engulfing Patterns', 1, 'article', 'html', false, false),
('les-t3-3.3', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.3: Hammer và Shooting Star', 2, 'article', 'html', false, false),
('les-t3-3.4', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.4: Three Methods Pattern', 3, 'article', 'html', false, false),
('les-t3-3.5', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.5: Candlesticks Làm Xác Nhận', 4, 'article', 'html', false, false),
('les-t3-3.6', 'mod-t3-ch3', 'course-tier3-trading-mastery', 'Bài 3.6: Ví Dụ Thực Tế Candlesticks', 5, 'article', 'html', false, false),
('les-t3-4.1', 'mod-t3-ch4', 'course-tier3-trading-mastery', 'Bài 4.1: Cup and Handle - Cốc và Tay Cầm', 0, 'article', 'html', false, false),
('les-t3-4.2', 'mod-t3-ch4', 'course-tier3-trading-mastery', 'Bài 4.2: Falling Three Methods', 1, 'article', 'html', false, false),
('les-t3-4.3', 'mod-t3-ch4', 'course-tier3-trading-mastery', 'Bài 4.3: Rising Three Methods', 2, 'article', 'html', false, false),
('les-t3-4.4', 'mod-t3-ch4', 'course-tier3-trading-mastery', 'Bài 4.4: Kết Hợp Advanced Patterns Với GEM Zones', 3, 'article', 'html', false, false),
('les-t3-4.5', 'mod-t3-ch4', 'course-tier3-trading-mastery', 'Bài 4.5: Ví Dụ Thực Tế Advanced Patterns', 4, 'article', 'html', false, false),
('les-t3-5.1', 'mod-t3-ch5', 'course-tier3-trading-mastery', 'Bài 5.1: Giới Thiệu GEM AI Brain', 0, 'article', 'html', false, false),
('les-t3-5.2', 'mod-t3-ch5', 'course-tier3-trading-mastery', 'Bài 5.2: Cách Đọc AI Signals', 1, 'article', 'html', false, false),
('les-t3-5.3', 'mod-t3-ch5', 'course-tier3-trading-mastery', 'Bài 5.3: Thiết Lập Cảnh Báo Tự Động', 2, 'article', 'html', false, false),
('les-t3-5.4', 'mod-t3-ch5', 'course-tier3-trading-mastery', 'Bài 5.4: AI + Phân Tích Con Người', 3, 'article', 'html', false, false),
('les-t3-5.5', 'mod-t3-ch5', 'course-tier3-trading-mastery', 'Bài 5.5: Ví Dụ AI Signals', 4, 'article', 'html', false, false),
('les-t3-6.1', 'mod-t3-ch6', 'course-tier3-trading-mastery', 'Bài 6.1: Whale Là Ai?', 0, 'article', 'html', false, false),
('les-t3-6.2', 'mod-t3-ch6', 'course-tier3-trading-mastery', 'Bài 6.2: Phát Hiện Lệnh Lớn', 1, 'article', 'html', false, false),
('les-t3-6.3', 'mod-t3-ch6', 'course-tier3-trading-mastery', 'Bài 6.3: Phân Tích Order Flow', 2, 'article', 'html', false, false),
('les-t3-6.4', 'mod-t3-ch6', 'course-tier3-trading-mastery', 'Bài 6.4: Tích Hợp Whale Signals', 3, 'article', 'html', false, false),
('les-t3-6.5', 'mod-t3-ch6', 'course-tier3-trading-mastery', 'Bài 6.5: Ví Dụ Whale Tracking', 4, 'article', 'html', false, false),
('les-t3-7.1', 'mod-t3-ch7', 'course-tier3-trading-mastery', 'Bài 7.1: Quản Lý Danh Mục', 0, 'article', 'html', false, false),
('les-t3-7.2', 'mod-t3-ch7', 'course-tier3-trading-mastery', 'Bài 7.2: Kiểm Soát Drawdown', 1, 'article', 'html', false, false),
('les-t3-7.3', 'mod-t3-ch7', 'course-tier3-trading-mastery', 'Bài 7.3: Tâm Lý Giao Dịch Chuyên Sâu', 2, 'article', 'html', false, false),
('les-t3-7.4', 'mod-t3-ch7', 'course-tier3-trading-mastery', 'Bài 7.4: Chiến Lược Giao Dịch Nâng Cao', 3, 'article', 'html', false, false),
('les-t3-7.5', 'mod-t3-ch7', 'course-tier3-trading-mastery', 'Bài 7.5: Tốt Nghiệp & Đối Tác', 4, 'article', 'html', false, false),
('les-t3-8.1', 'mod-t3-ch8', 'course-tier3-trading-mastery', 'Bài 8.1: Con Người Cũ và Con Người Mới', 0, 'article', 'html', false, false),
('les-t3-8.2', 'mod-t3-ch8', 'course-tier3-trading-mastery', 'Bài 8.2: Bản Đồ Hành Trình Của Bạn', 1, 'article', 'html', false, false),
('les-t3-8.3', 'mod-t3-ch8', 'course-tier3-trading-mastery', 'Bài 8.3: Sự Thay Đổi Thực Sự', 2, 'article', 'html', false, false),
('les-t3-8.4', 'mod-t3-ch8', 'course-tier3-trading-mastery', 'Bài 8.4: Điều Khiến Bạn Khác Biệt', 3, 'article', 'html', false, false),
('les-t3-9.1', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.1: Ngã Ba Đường - Bạn Đang Đứng Ở Đâu', 0, 'article', 'html', false, false),
('les-t3-9.2', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.2: Cơ Hội Tiếp Theo', 1, 'article', 'html', false, false),
('les-t3-9.3', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.3: Cơ Hội Đối Tác Cao Cấp', 2, 'article', 'html', false, false),
('les-t3-9.4', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.4: Câu Chuyện Thành Công Elite', 3, 'article', 'html', false, false),
('les-t3-9.5', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.5: Lợi Thế Đi Sớm', 4, 'article', 'html', false, false),
('les-t3-9.6', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.6: Khung Quyết Định', 5, 'article', 'html', false, false),
('les-t3-9.7', 'mod-t3-ch9', 'course-tier3-trading-mastery', 'Bài 9.7: Các Bước Tiếp Theo', 6, 'article', 'html', false, false);
