/**
 * Export Service for Chatbot
 * Handles exporting conversations to various formats
 */

class ExportService {
  /**
   * Export chat to text format
   */
  exportToText(messages, fileName = 'gem-chat-export') {
    if (!messages || messages.length === 0) {
      alert('Không có tin nhắn để export!');
      return;
    }

    const timestamp = new Date().toLocaleString('vi-VN');
    let textContent = `GEMRAL CHATBOT - Chat Export\n`;
    textContent += `Exported: ${timestamp}\n`;
    textContent += `${'='.repeat(60)}\n\n`;

    messages.forEach((msg, idx) => {
      if (msg.type === 'user') {
        textContent += `[USER] ${new Date(msg.timestamp).toLocaleString('vi-VN')}\n`;
        textContent += `${msg.content}\n\n`;
      } else if (msg.type === 'bot') {
        textContent += `[GEMRAL] ${new Date(msg.timestamp).toLocaleString('vi-VN')}\n`;
        textContent += `${msg.content}\n\n`;
      } else if (msg.type === 'system') {
        textContent += `[SYSTEM] ${new Date(msg.timestamp).toLocaleString('vi-VN')}\n`;
        textContent += `${msg.content}\n\n`;
      }
      textContent += `${'-'.repeat(60)}\n\n`;
    });

    textContent += `\n${'='.repeat(60)}\n`;
    textContent += `Total messages: ${messages.length}\n`;
    textContent += `Generated by Gemral - https://gemral.com\n`;

    // Create blob and download
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    this.downloadBlob(blob, `${fileName}-${Date.now()}.txt`);
  }

  /**
   * Export chat to JSON format (for backup/restore)
   */
  exportToJSON(messages, conversationHistory, fileName = 'gem-chat-backup') {
    if (!messages || messages.length === 0) {
      alert('Không có tin nhắn để export!');
      return;
    }

    const exportData = {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      messages: messages,
      conversationHistory: conversationHistory || [],
      metadata: {
        totalMessages: messages.length,
        platform: 'Gemral',
        chatbot: 'Gemral'
      }
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    this.downloadBlob(blob, `${fileName}-${Date.now()}.json`);
  }

  /**
   * Export chat to Markdown format
   */
  exportToMarkdown(messages, fileName = 'gem-chat-export') {
    if (!messages || messages.length === 0) {
      alert('Không có tin nhắn để export!');
      return;
    }

    const timestamp = new Date().toLocaleString('vi-VN');
    let mdContent = `# GEMRAL CHATBOT - Chat Export\n\n`;
    mdContent += `**Exported:** ${timestamp}\n\n`;
    mdContent += `---\n\n`;

    messages.forEach((msg, idx) => {
      if (msg.type === 'user') {
        mdContent += `### 👤 User\n`;
        mdContent += `*${new Date(msg.timestamp).toLocaleString('vi-VN')}*\n\n`;
        mdContent += `${msg.content}\n\n`;
      } else if (msg.type === 'bot') {
        mdContent += `### 🔮 Gemral\n`;
        mdContent += `*${new Date(msg.timestamp).toLocaleString('vi-VN')}*\n\n`;
        mdContent += `${msg.content}\n\n`;
      } else if (msg.type === 'system') {
        mdContent += `### ⚠️ System\n`;
        mdContent += `*${new Date(msg.timestamp).toLocaleString('vi-VN')}*\n\n`;
        mdContent += `${msg.content}\n\n`;
      }
      mdContent += `---\n\n`;
    });

    mdContent += `\n**Total messages:** ${messages.length}\n\n`;
    mdContent += `*Generated by Gemral - https://gemral.com*\n`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    this.downloadBlob(blob, `${fileName}-${Date.now()}.md`);
  }

  /**
   * Share chat via Web Share API (mobile-friendly)
   */
  async shareChat(messages) {
    if (!messages || messages.length === 0) {
      alert('Không có tin nhắn để share!');
      return;
    }

    // Create shareable text
    const lastMessage = messages[messages.length - 1];
    const shareText = lastMessage.type === 'bot'
      ? `Gemral says:\n\n${lastMessage.content.substring(0, 200)}...`
      : `Check out my Gemral chat!`;

    // Check if Web Share API is supported
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Gemral Chatbot',
          text: shareText,
          url: window.location.href
        });
        console.log('✅ Shared successfully');
      } catch (error) {
        if (error.name !== 'AbortError') {
          console.error('Share failed:', error);
          this.fallbackShare(shareText);
        }
      }
    } else {
      this.fallbackShare(shareText);
    }
  }

  /**
   * Fallback share - copy to clipboard
   */
  fallbackShare(text) {
    navigator.clipboard.writeText(text).then(() => {
      alert('✅ Đã copy vào clipboard! Bạn có thể paste để share.');
    }).catch(err => {
      console.error('Failed to copy:', err);
      alert('❌ Không thể copy. Vui lòng thử lại.');
    });
  }

  /**
   * Copy specific message to clipboard
   */
  async copyMessage(messageContent) {
    try {
      await navigator.clipboard.writeText(messageContent);
      return true;
    } catch (error) {
      console.error('Failed to copy message:', error);
      return false;
    }
  }

  /**
   * Download blob helper
   */
  downloadBlob(blob, fileName) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Print chat conversation
   */
  printChat(messages) {
    if (!messages || messages.length === 0) {
      alert('Không có tin nhắn để print!');
      return;
    }

    const timestamp = new Date().toLocaleString('vi-VN');
    let printContent = `
      <html>
        <head>
          <title>Gemral Chatbot - Print</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
              background: white;
              color: #000;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              border-bottom: 3px solid #FFBD59;
              padding-bottom: 20px;
            }
            .header h1 {
              color: #1a1a2e;
              margin: 0;
            }
            .timestamp {
              color: #666;
              font-size: 14px;
              margin-top: 10px;
            }
            .message {
              margin-bottom: 30px;
              padding: 15px;
              border-radius: 8px;
              page-break-inside: avoid;
            }
            .message.user {
              background: #f0f0f0;
              border-left: 4px solid #FFBD59;
            }
            .message.bot {
              background: #e8f4f8;
              border-left: 4px solid #00D9FF;
            }
            .message.system {
              background: #fff3cd;
              border-left: 4px solid #ff6b6b;
            }
            .message-header {
              font-weight: bold;
              margin-bottom: 8px;
              font-size: 14px;
            }
            .message-time {
              color: #666;
              font-size: 12px;
            }
            .message-content {
              white-space: pre-wrap;
              line-height: 1.6;
              margin-top: 10px;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 2px solid #e0e0e0;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🔮 Gemral CHATBOT</h1>
            <div class="timestamp">Exported: ${timestamp}</div>
          </div>
    `;

    messages.forEach(msg => {
      const messageType = msg.type || 'bot';
      const typeLabel = messageType === 'user' ? '👤 User' : messageType === 'bot' ? '🔮 Gemral' : '⚠️ System';

      printContent += `
        <div class="message ${messageType}">
          <div class="message-header">${typeLabel}</div>
          <div class="message-time">${new Date(msg.timestamp).toLocaleString('vi-VN')}</div>
          <div class="message-content">${msg.content}</div>
        </div>
      `;
    });

    printContent += `
          <div class="footer">
            <p>Total messages: ${messages.length}</p>
            <p>Generated by Gemral - https://gemral.com</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();

    // Auto-print after content loads
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
}

// Export singleton instance
export const exportService = new ExportService();
