/**
 * PDF Export Service
 * Export chat sessions and readings to PDF
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

class PDFExportService {
  /**
   * Export chat session to PDF
   */
  async exportChatSession(messages, metadata = {}) {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      let yPosition = 20;

      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(139, 92, 246); // Purple
      pdf.text('GEM Chatbot - Chat Session', pageWidth / 2, yPosition, { align: 'center' });

      yPosition += 10;
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Exported: ${new Date().toLocaleString('vi-VN')}`, pageWidth / 2, yPosition, { align: 'center' });

      if (metadata.userName) {
        yPosition += 5;
        pdf.text(`User: ${metadata.userName}`, pageWidth / 2, yPosition, { align: 'center' });
      }

      yPosition += 15;

      // Messages
      for (const msg of messages) {
        // Check if need new page
        if (yPosition > pageHeight - 30) {
          pdf.addPage();
          yPosition = 20;
        }

        // Skip system messages
        if (msg.type === 'system' || msg.type === 'products') continue;

        // User or Bot label
        pdf.setFontSize(12);
        const isUser = msg.type === 'user';
        pdf.setTextColor(isUser ? 100 : 139, isUser ? 100 : 92, isUser ? 100 : 246);
        pdf.text(isUser ? 'You:' : 'Master Jennie:', margin, yPosition);

        yPosition += 7;

        // Message content - clean and wrap text
        pdf.setFontSize(10);
        pdf.setTextColor(50, 50, 50);

        const cleanContent = this.cleanText(msg.content);
        const lines = pdf.splitTextToSize(cleanContent, contentWidth);

        // Check if lines fit on current page
        const linesHeight = lines.length * 5;
        if (yPosition + linesHeight > pageHeight - 20) {
          pdf.addPage();
          yPosition = 20;
        }

        pdf.text(lines, margin, yPosition);
        yPosition += linesHeight + 10;
      }

      // Footer
      const footerY = pageHeight - 10;
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by GEM Trading Academy', pageWidth / 2, footerY, { align: 'center' });

      // Save
      const filename = `GEM-Chat-${Date.now()}.pdf`;
      pdf.save(filename);

      return { success: true, filename };
    } catch (error) {
      console.error('PDF export error:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Export element as image in PDF
   */
  async exportAsImage(elementId) {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error('Element not found');
      }

      const canvas = await html2canvas(element, {
        backgroundColor: '#0a0a0f',
        scale: 2,
        logging: false
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');

      const imgWidth = pdf.internal.pageSize.getWidth();
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

      const filename = `GEM-Reading-${Date.now()}.pdf`;
      pdf.save(filename);

      return { success: true, filename };
    } catch (error) {
      console.error('Image export error:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Clean text from markdown and special characters
   */
  cleanText(text) {
    if (!text) return '';

    return text
      .replace(/\*\*/g, '')  // Remove bold
      .replace(/\*/g, '')    // Remove italic
      .replace(/##/g, '')    // Remove h2
      .replace(/###/g, '')   // Remove h3
      .replace(/`/g, '')     // Remove code blocks
      .trim();
  }

  /**
   * Export specific reading (I Ching or Tarot)
   */
  async exportReading(reading, type = 'iching') {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      let yPosition = 20;

      // Header
      pdf.setFontSize(22);
      pdf.setTextColor(139, 92, 246);
      pdf.text('GEM Chatbot Reading', pageWidth / 2, yPosition, { align: 'center' });

      yPosition += 10;
      pdf.setFontSize(14);
      pdf.setTextColor(255, 189, 89);
      pdf.text(reading.name || reading.title, pageWidth / 2, yPosition, { align: 'center' });

      yPosition += 15;

      // Content
      pdf.setFontSize(11);
      pdf.setTextColor(50, 50, 50);

      if (reading.content) {
        const lines = pdf.splitTextToSize(this.cleanText(reading.content), contentWidth);
        pdf.text(lines, margin, yPosition);
      }

      // Footer
      yPosition = pdf.internal.pageSize.getHeight() - 15;
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`${new Date().toLocaleString('vi-VN')}`, pageWidth / 2, yPosition, { align: 'center' });

      yPosition += 5;
      pdf.text('GEM Trading Academy', pageWidth / 2, yPosition, { align: 'center' });

      const filename = `GEM-${type}-${Date.now()}.pdf`;
      pdf.save(filename);

      return { success: true, filename };
    } catch (error) {
      console.error('Reading export error:', error);
      return { success: false, error: error.message };
    }
  }
}

export const pdfExportService = new PDFExportService();
