/**
 * Share Service
 * Social media sharing and Web Share API
 */

class ShareService {
  /**
   * Share reading using native share or fallback
   */
  async shareReading(reading, method = 'native') {
    const shareData = {
      title: 'GEM Chatbot - My Reading',
      text: this.formatReadingText(reading),
      url: window.location.href
    };

    if (method === 'native' && this.isNativeShareSupported()) {
      try {
        await navigator.share(shareData);
        return { success: true, method: 'native' };
      } catch (error) {
        // User cancelled or error occurred
        if (error.name !== 'AbortError') {
          console.error('Share failed:', error);
        }
        return { success: false, error };
      }
    }

    // Fallback to social media URLs
    return this.getSocialShareUrls(shareData);
  }

  /**
   * Share chat session
   */
  async shareChat(messages) {
    const shareText = this.formatChatText(messages);
    const shareData = {
      title: 'GEM Chatbot - Chat Session',
      text: shareText,
      url: window.location.href
    };

    if (this.isNativeShareSupported()) {
      try {
        await navigator.share(shareData);
        return { success: true, method: 'native' };
      } catch (error) {
        if (error.name !== 'AbortError') {
          console.error('Share failed:', error);
        }
        return { success: false, error };
      }
    }

    // Fallback
    return this.getSocialShareUrls(shareData);
  }

  /**
   * Get social media share URLs
   */
  getSocialShareUrls(data) {
    const encodedText = encodeURIComponent(data.text);
    const encodedUrl = encodeURIComponent(data.url);

    return {
      success: true,
      method: 'fallback',
      urls: {
        facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`,
        twitter: `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`,
        telegram: `https://t.me/share/url?url=${encodedUrl}&text=${encodedText}`,
        zalo: `https://zalo.me/share?url=${encodedUrl}&text=${encodedText}`,
        copy: 'clipboard'
      }
    };
  }

  /**
   * Copy to clipboard
   */
  async copyToClipboard(text) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
        return { success: true };
      }

      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);

      return { success: true };
    } catch (error) {
      console.error('Copy failed:', error);
      return { success: false, error };
    }
  }

  /**
   * Format reading for sharing
   */
  formatReadingText(reading) {
    let text = `${reading.name || reading.title}\n\n`;

    if (reading.content) {
      text += reading.content.slice(0, 200);
      if (reading.content.length > 200) {
        text += '...';
      }
    }

    text += '\n\n📚 Generated by GEM Chatbot';
    return text;
  }

  /**
   * Format chat session for sharing
   */
  formatChatText(messages) {
    let text = 'My GEM Chatbot Session:\n\n';

    // Include last 3 messages
    const recentMessages = messages.slice(-3).filter(m => m.type !== 'system' && m.type !== 'products');

    recentMessages.forEach((msg, idx) => {
      const label = msg.type === 'user' ? 'Me' : 'Master Jennie';
      const content = msg.content.slice(0, 100);
      text += `${label}: ${content}${msg.content.length > 100 ? '...' : ''}\n\n`;
    });

    text += '📚 Generated by GEM Chatbot';
    return text;
  }

  /**
   * Check if native share is supported
   */
  isNativeShareSupported() {
    return navigator.share !== undefined;
  }

  /**
   * Open social share in new window
   */
  openShareWindow(url) {
    const width = 600;
    const height = 400;
    const left = (window.innerWidth - width) / 2;
    const top = (window.innerHeight - height) / 2;

    window.open(
      url,
      'share',
      `width=${width},height=${height},left=${left},top=${top},toolbar=no,location=no,menubar=no`
    );
  }
}

export const shareService = new ShareService();
