-- =====================================================
-- ADMIN AI DAILY REPORTS - ROI PROOF SYSTEM PHASE E
-- File: migrations/20260208_create_admin_ai_daily_reports.sql
-- Created: February 8, 2026
-- Description: Admin AI reports table with Gemini analysis
-- =====================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- TABLE: admin_ai_daily_reports
-- Stores daily AI-generated reports for admin dashboard
-- Generated by Gemini 2.5 Flash at 00:15 UTC
-- =====================================================
CREATE TABLE IF NOT EXISTS admin_ai_daily_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Report date (one per day)
  report_date DATE NOT NULL UNIQUE,

  -- Status
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'completed', 'failed')),

  -- Raw data snapshot (input to AI)
  raw_data JSONB NOT NULL DEFAULT '{}',

  -- AI-generated content (Vietnamese with diacritics)
  ai_summary TEXT, -- 2-3 paragraph summary
  ai_insights JSONB DEFAULT '[]', -- Array of insight objects
  ai_recommendations JSONB DEFAULT '[]', -- Array of recommendation objects
  ai_warnings JSONB DEFAULT '[]', -- Array of warning objects

  -- KPI snapshot for quick display
  kpi_total_users INTEGER DEFAULT 0,
  kpi_active_users INTEGER DEFAULT 0,
  kpi_new_users_today INTEGER DEFAULT 0,
  kpi_total_trades INTEGER DEFAULT 0,
  kpi_avg_win_rate DECIMAL(5, 2),
  kpi_total_pnl DECIMAL(20, 2) DEFAULT 0,
  kpi_accounts_healthy INTEGER DEFAULT 0,
  kpi_accounts_warning INTEGER DEFAULT 0,
  kpi_accounts_danger INTEGER DEFAULT 0,
  kpi_accounts_burned INTEGER DEFAULT 0,
  kpi_accounts_wiped INTEGER DEFAULT 0,
  kpi_burn_rate_pct DECIMAL(5, 2),
  kpi_ritual_completion_rate DECIMAL(5, 2),
  kpi_scanner_usage_pct DECIMAL(5, 2),
  kpi_ai_blocks_today INTEGER DEFAULT 0,
  kpi_ai_conversations INTEGER DEFAULT 0,

  -- Processing metadata
  processing_started_at TIMESTAMPTZ,
  processing_completed_at TIMESTAMPTZ,
  processing_duration_ms INTEGER,
  ai_model_used VARCHAR(50),
  ai_tokens_used INTEGER,
  error_message TEXT,
  retry_count INTEGER DEFAULT 0,

  -- Notification tracking
  admin_notified BOOLEAN DEFAULT FALSE,
  admin_notified_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_reports_date
  ON admin_ai_daily_reports(report_date DESC);
CREATE INDEX IF NOT EXISTS idx_ai_reports_status
  ON admin_ai_daily_reports(status);
CREATE INDEX IF NOT EXISTS idx_ai_reports_pending
  ON admin_ai_daily_reports(status)
  WHERE status IN ('pending', 'processing');

-- RLS Policies (admin only)
ALTER TABLE admin_ai_daily_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_only_ai_reports" ON admin_ai_daily_reports;
CREATE POLICY "admin_only_ai_reports" ON admin_ai_daily_reports
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'super_admin')
    )
  );

DROP POLICY IF EXISTS "service_all_ai_reports" ON admin_ai_daily_reports;
CREATE POLICY "service_all_ai_reports" ON admin_ai_daily_reports
  FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- Grant permissions
GRANT ALL ON admin_ai_daily_reports TO service_role;


-- =====================================================
-- TABLE: proof_export_history
-- Tracks HTML exports for marketing
-- =====================================================
CREATE TABLE IF NOT EXISTS proof_export_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Export info
  exported_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  export_date DATE NOT NULL,
  export_type VARCHAR(30) NOT NULL DEFAULT 'html'
    CHECK (export_type IN ('html', 'pdf', 'json', 'csv')),

  -- Date range for export
  date_range_start DATE,
  date_range_end DATE,

  -- File info
  file_url TEXT,
  file_size_bytes INTEGER,
  file_name VARCHAR(200),

  -- KPI snapshot at export time
  kpi_snapshot JSONB DEFAULT '{}',

  -- Export configuration
  config JSONB DEFAULT '{}',

  -- Status
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  error_message TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_export_history_date
  ON proof_export_history(export_date DESC);
CREATE INDEX IF NOT EXISTS idx_export_history_user
  ON proof_export_history(exported_by);

-- RLS (admin only)
ALTER TABLE proof_export_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_only_export_history" ON proof_export_history;
CREATE POLICY "admin_only_export_history" ON proof_export_history
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'super_admin')
    )
  );

DROP POLICY IF EXISTS "service_all_export_history" ON proof_export_history;
CREATE POLICY "service_all_export_history" ON proof_export_history
  FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- Grant permissions
GRANT ALL ON proof_export_history TO service_role;


-- =====================================================
-- FUNCTION: get_admin_roi_summary
-- Returns comprehensive ROI metrics for admin dashboard
-- =====================================================
CREATE OR REPLACE FUNCTION get_admin_roi_summary(
  p_days INTEGER DEFAULT 30
)
RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_start_date DATE;
BEGIN
  v_start_date := CURRENT_DATE - p_days;

  SELECT jsonb_build_object(
    'period', jsonb_build_object(
      'start_date', v_start_date,
      'end_date', CURRENT_DATE,
      'days', p_days
    ),

    -- User metrics
    'users', jsonb_build_object(
      'total', (SELECT COUNT(*) FROM profiles),
      'active_30d', (SELECT COUNT(DISTINCT user_id) FROM user_daily_composite WHERE composite_date >= v_start_date),
      'new_today', (SELECT COUNT(*) FROM profiles WHERE DATE(created_at) = CURRENT_DATE),
      'by_tier', (
        SELECT jsonb_object_agg(COALESCE(scanner_tier, 'FREE'), cnt)
        FROM (SELECT scanner_tier, COUNT(*) as cnt FROM profiles GROUP BY scanner_tier) sub
      ),
      'by_karma_level', (
        SELECT jsonb_object_agg(COALESCE(karma_level, 'student'), cnt)
        FROM (SELECT karma_level, COUNT(*) as cnt FROM profiles GROUP BY karma_level) sub
      )
    ),

    -- Account health distribution
    'health', jsonb_build_object(
      'distribution', (
        SELECT jsonb_build_object(
          'healthy', COUNT(*) FILTER (WHERE health_status = 'healthy'),
          'warning', COUNT(*) FILTER (WHERE health_status = 'warning'),
          'danger', COUNT(*) FILTER (WHERE health_status = 'danger'),
          'burned', COUNT(*) FILTER (WHERE health_status = 'burned'),
          'wiped', COUNT(*) FILTER (WHERE health_status = 'wiped')
        )
        FROM account_health_snapshots
        WHERE snapshot_date = CURRENT_DATE
      ),
      'burn_rate_pct', (
        SELECT ROUND(
          COUNT(*) FILTER (WHERE health_status IN ('burned', 'wiped'))::DECIMAL /
          NULLIF(COUNT(*), 0) * 100, 2
        )
        FROM account_health_snapshots
        WHERE snapshot_date = CURRENT_DATE
      ),
      'burn_events_today', (
        SELECT COUNT(*)
        FROM account_burn_events
        WHERE event_date = CURRENT_DATE AND direction = 'degrading'
      ),
      'recovery_events_today', (
        SELECT COUNT(*)
        FROM account_burn_events
        WHERE event_date = CURRENT_DATE AND direction = 'recovering'
      )
    ),

    -- Trading metrics
    'trading', jsonb_build_object(
      'total_trades', (
        SELECT COALESCE(SUM(trades_total), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'avg_win_rate', (
        SELECT ROUND(AVG(win_rate)::NUMERIC, 2)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date AND win_rate IS NOT NULL
      ),
      'total_pnl', (
        SELECT COALESCE(SUM(pnl_total), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'scanner_usage_pct', (
        SELECT ROUND(
          COUNT(*) FILTER (WHERE used_scanner)::DECIMAL /
          NULLIF(COUNT(*), 0) * 100, 2
        )
        FROM user_daily_composite
        WHERE composite_date >= v_start_date AND trades_total > 0
      ),
      'scanner_vs_manual', (
        SELECT jsonb_build_object(
          'scanner_win_rate', ROUND(AVG(scanner_win_rate)::NUMERIC, 2),
          'manual_win_rate', ROUND(AVG(manual_win_rate)::NUMERIC, 2),
          'advantage', ROUND(
            COALESCE(AVG(scanner_win_rate), 0) - COALESCE(AVG(manual_win_rate), 0)
          , 2)
        )
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      )
    ),

    -- Ritual & Wellness
    'wellness', jsonb_build_object(
      'total_rituals', (
        SELECT COALESCE(SUM(rituals_completed), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'avg_rituals_per_user', (
        SELECT ROUND(AVG(rituals_completed)::NUMERIC, 2)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'morning_ritual_rate', (
        SELECT ROUND(
          COUNT(*) FILTER (WHERE morning_ritual_done)::DECIMAL /
          NULLIF(COUNT(*), 0) * 100, 2
        )
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'ritual_boost', (
        SELECT jsonb_build_object(
          'with_ritual_win_rate', (
            SELECT ROUND(AVG(win_rate)::NUMERIC, 2)
            FROM user_daily_composite
            WHERE morning_ritual_done AND trades_total > 0
          ),
          'without_ritual_win_rate', (
            SELECT ROUND(AVG(win_rate)::NUMERIC, 2)
            FROM user_daily_composite
            WHERE NOT morning_ritual_done AND trades_total > 0
          )
        )
      )
    ),

    -- Discipline
    'discipline', jsonb_build_object(
      'avg_score', (
        SELECT ROUND(AVG(discipline_score_avg)::NUMERIC, 2)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date AND discipline_score_avg IS NOT NULL
      ),
      'high_discipline_users', (
        SELECT COUNT(DISTINCT user_id)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date AND discipline_score_avg >= 80
      ),
      'revenge_trades_total', (
        SELECT COALESCE(SUM(revenge_trades_count), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      )
    ),

    -- AI Interactions
    'ai', jsonb_build_object(
      'total_conversations', (
        SELECT COALESCE(SUM(ai_conversations), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      ),
      'blocks_triggered', (
        SELECT COALESCE(SUM(ai_blocks_triggered), 0)
        FROM user_daily_composite
        WHERE composite_date >= v_start_date
      )
    ),

    -- Cohort comparison
    'cohorts', (
      SELECT jsonb_agg(cohort_data)
      FROM (
        SELECT jsonb_build_object(
          'practice_level', practice_level,
          'users', COUNT(*),
          'avg_win_rate', ROUND(AVG(avg_win_rate_30d)::NUMERIC, 2),
          'burn_rate', ROUND(
            COUNT(*) FILTER (WHERE burned_days_30d > 0 OR wiped_days_30d > 0)::DECIMAL /
            NULLIF(COUNT(*), 0) * 100, 2
          )
        ) as cohort_data
        FROM user_practice_profile
        WHERE profile_date = (SELECT MAX(profile_date) FROM user_practice_profile)
        GROUP BY practice_level
      ) sub
    ),

    -- Karma vs burn correlation
    'karma_burn_correlation', (
      SELECT jsonb_agg(karma_data)
      FROM (
        SELECT jsonb_build_object(
          'karma_level', karma_level,
          'users', COUNT(DISTINCT user_id),
          'burn_rate', ROUND(
            COUNT(*) FILTER (WHERE health_status IN ('burned', 'wiped'))::DECIMAL /
            NULLIF(COUNT(*), 0) * 100, 2
          ),
          'avg_win_rate', ROUND(AVG(win_rate)::NUMERIC, 2)
        ) as karma_data
        FROM user_daily_composite
        WHERE composite_date >= v_start_date AND karma_level IS NOT NULL
        GROUP BY karma_level
      ) sub
    ),

    -- Timestamp
    'generated_at', NOW()

  ) INTO v_result;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================
-- FUNCTION: get_latest_ai_report
-- Returns the most recent completed AI report
-- =====================================================
CREATE OR REPLACE FUNCTION get_latest_ai_report()
RETURNS JSONB AS $$
DECLARE
  v_report RECORD;
BEGIN
  SELECT *
  INTO v_report
  FROM admin_ai_daily_reports
  WHERE status = 'completed'
  ORDER BY report_date DESC
  LIMIT 1;

  IF v_report IS NULL THEN
    RETURN jsonb_build_object('success', FALSE, 'error', 'No completed reports found');
  END IF;

  RETURN jsonb_build_object(
    'success', TRUE,
    'report_date', v_report.report_date,
    'summary', v_report.ai_summary,
    'insights', v_report.ai_insights,
    'recommendations', v_report.ai_recommendations,
    'warnings', v_report.ai_warnings,
    'kpis', jsonb_build_object(
      'total_users', v_report.kpi_total_users,
      'active_users', v_report.kpi_active_users,
      'avg_win_rate', v_report.kpi_avg_win_rate,
      'burn_rate', v_report.kpi_burn_rate_pct,
      'scanner_usage', v_report.kpi_scanner_usage_pct,
      'ritual_rate', v_report.kpi_ritual_completion_rate
    ),
    'generated_at', v_report.processing_completed_at
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================
-- GRANTS
-- =====================================================
GRANT EXECUTE ON FUNCTION get_admin_roi_summary(INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION get_latest_ai_report() TO authenticated;


-- =====================================================
-- COMMENTS
-- =====================================================
COMMENT ON TABLE admin_ai_daily_reports IS
  'Daily AI-generated reports for admin ROI dashboard. Generated by Gemini 2.5 Flash.';

COMMENT ON TABLE proof_export_history IS
  'Tracks HTML/PDF exports of ROI proof data for marketing purposes.';

COMMENT ON FUNCTION get_admin_roi_summary IS
  'Returns comprehensive ROI summary for admin dashboard and AI report generation.';

COMMENT ON FUNCTION get_latest_ai_report IS
  'Returns the most recent completed AI report for dashboard display.';
