-- ═══════════════════════════════════════════════════════════════════════════
-- GEM AI Trading Brain - Database Schema
-- Admin-only AI trading assistant tables
-- Date: 2026-02-04
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════
-- TABLE: admin_ai_conversations
-- Stores conversation metadata for admin AI chats
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS admin_ai_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Metadata
  title TEXT,
  symbol TEXT,
  timeframe TEXT,

  -- Stats
  message_count INT DEFAULT 0,
  last_message_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Admin only
ALTER TABLE admin_ai_conversations ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if exists
DROP POLICY IF EXISTS "admin_ai_conversations_admin_only" ON admin_ai_conversations;

CREATE POLICY "admin_ai_conversations_admin_only" ON admin_ai_conversations
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND (
        profiles.is_admin = TRUE OR
        profiles.role = 'admin' OR
        profiles.role = 'ADMIN' OR
        profiles.scanner_tier = 'ADMIN' OR
        profiles.chatbot_tier = 'ADMIN'
      )
    )
  );

-- Index for fast lookup
CREATE INDEX IF NOT EXISTS idx_admin_ai_conversations_user
  ON admin_ai_conversations(user_id, created_at DESC);


-- ═══════════════════════════════════════════════════════════
-- TABLE: admin_ai_messages
-- Stores individual messages in admin AI conversations
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS admin_ai_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES admin_ai_conversations(id) ON DELETE CASCADE,

  -- Content
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,

  -- Context snapshot (for debugging/analysis)
  context_snapshot JSONB,

  -- AI metadata
  tokens_used INT,
  response_time_ms INT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS via parent conversation
ALTER TABLE admin_ai_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_ai_messages_via_conversation" ON admin_ai_messages;

CREATE POLICY "admin_ai_messages_via_conversation" ON admin_ai_messages
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM admin_ai_conversations c
      WHERE c.id = admin_ai_messages.conversation_id
    )
  );

-- Index for fast message retrieval
CREATE INDEX IF NOT EXISTS idx_admin_ai_messages_conversation
  ON admin_ai_messages(conversation_id, created_at DESC);


-- ═══════════════════════════════════════════════════════════
-- TABLE: admin_ai_alerts
-- Stores proactive alerts generated by the AI system
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS admin_ai_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Alert info
  alert_type TEXT NOT NULL CHECK (alert_type IN (
    'approaching_sl', 'hit_sl', 'hit_tp',
    'pattern_invalidated', 'zone_broken',
    'sudden_volume', 'divergence', 'risk_warning',
    'large_profit', 'large_loss', 'breakeven'
  )),
  symbol TEXT NOT NULL,
  timeframe TEXT,
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),

  -- Content
  title TEXT NOT NULL,
  message TEXT NOT NULL,

  -- Related data (for context)
  pattern_data JSONB,
  zone_data JSONB,
  position_data JSONB,

  -- Status
  is_read BOOLEAN DEFAULT FALSE,
  is_dismissed BOOLEAN DEFAULT FALSE,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  read_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '24 hours')
);

-- RLS: Admin only
ALTER TABLE admin_ai_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_ai_alerts_admin_only" ON admin_ai_alerts;

CREATE POLICY "admin_ai_alerts_admin_only" ON admin_ai_alerts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND (
        profiles.is_admin = TRUE OR
        profiles.role = 'admin' OR
        profiles.role = 'ADMIN' OR
        profiles.scanner_tier = 'ADMIN'
      )
    )
  );

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_admin_ai_alerts_unread
  ON admin_ai_alerts(user_id, is_read)
  WHERE is_read = FALSE;

CREATE INDEX IF NOT EXISTS idx_admin_ai_alerts_expires
  ON admin_ai_alerts(expires_at)
  WHERE is_dismissed = FALSE;

CREATE INDEX IF NOT EXISTS idx_admin_ai_alerts_type
  ON admin_ai_alerts(user_id, alert_type, created_at DESC);


-- ═══════════════════════════════════════════════════════════
-- FUNCTION: Update conversation message_count trigger
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_admin_ai_conversation_stats()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE admin_ai_conversations
    SET
      message_count = message_count + 1,
      last_message_at = NEW.created_at,
      updated_at = NOW()
    WHERE id = NEW.conversation_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE admin_ai_conversations
    SET
      message_count = GREATEST(0, message_count - 1),
      updated_at = NOW()
    WHERE id = OLD.conversation_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS trigger_update_admin_ai_conversation_stats ON admin_ai_messages;

CREATE TRIGGER trigger_update_admin_ai_conversation_stats
  AFTER INSERT OR DELETE ON admin_ai_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_admin_ai_conversation_stats();


-- ═══════════════════════════════════════════════════════════
-- FUNCTION: Clean up expired alerts (to be called via cron)
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION cleanup_expired_admin_ai_alerts()
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM admin_ai_alerts
  WHERE expires_at < NOW()
  AND is_dismissed = FALSE;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;


-- ═══════════════════════════════════════════════════════════
-- COMMENTS
-- ═══════════════════════════════════════════════════════════

COMMENT ON TABLE admin_ai_conversations IS 'GEM AI Trading Brain - Admin AI chat conversations';
COMMENT ON TABLE admin_ai_messages IS 'GEM AI Trading Brain - Individual messages in AI conversations';
COMMENT ON TABLE admin_ai_alerts IS 'GEM AI Trading Brain - Proactive trading alerts for admin';

COMMENT ON COLUMN admin_ai_alerts.alert_type IS 'Type of alert: approaching_sl, hit_sl, hit_tp, pattern_invalidated, zone_broken, sudden_volume, divergence, risk_warning, large_profit, large_loss, breakeven';
COMMENT ON COLUMN admin_ai_alerts.priority IS 'Alert priority: low, normal, high, urgent';
COMMENT ON COLUMN admin_ai_messages.context_snapshot IS 'JSON snapshot of trading context when message was sent (for debugging)';
